### ISSUE TITLE
I have a doubt

### ISSUE THREAD

**Issue by filipeborelli** [umzr/Telegram-Gmail-Bot-Google-Script-Version-#1]
I didn't understand very well how to implement this script, I did all the steps, but the emails are not sending on telegram
this part of the trigger I don't know where to find it

**Comment by umzr** [comment]
Oh Hi.

Sorry for the missing information. I thought no one would care my project. So I wrote the instructions ambiguously. 

Please stay tuned. I will write the full steps for the instructions. @filipeborelli

**Comment by umzr** [comment]
updated doc
