### ISSUE TITLE
Message length (4096 characters)

### ISSUE THREAD

**Issue by visitoid** [umzr/Telegram-Gmail-Bot-Google-Script-Version-#2]
In a telegramm, the message length is limited to 4096 characters. It is possible to make the script check the length of the message before sending it to the telegramm, and send only the first 4096 characters.

**Comment by umzr** [comment]
hi, I just updated my code.
please take a look

**Comment by visitoid** [comment]
08:00:50 Error
TypeError: The "length" property of the undefined object cannot be read.
searchUnreadEmail	@ google.gs:47

line 47: for (var j = 0; j < outputString.length; ++j) {

**Comment by visitoid** [comment]
I'm fixed the error. Thanks.

**Comment by umzr** [comment]
fixed
